-- Insert dummy items for design studio inventory
INSERT INTO items (name, description, category, available, damaged, in_use) VALUES
('Professional Camera - Canon EOS R5', 'Full-frame mirrorless camera, 45MP, excellent for product photography', 'Photography Equipment', 3, 0, 1),
('Studio Lighting Kit - 3 Piece', 'Professional LED lighting kit with adjustable color temperature', 'Lighting', 5, 1, 2),
('Tripod - Carbon Fiber Heavy Duty', 'Sturdy carbon fiber tripod with ball head, max height 6ft', 'Photography Equipment', 8, 0, 0),
('Backdrop Stand - Adjustable', 'Adjustable stand for 10ft wide backdrops, includes carry case', 'Studio Setup', 6, 1, 0),
('White Seamless Paper - 107" x 36"', 'Professional quality white seamless paper roll', 'Studio Supplies', 15, 2, 0),
('Green Screen - 6ft x 8ft', 'Portable green screen with stand and carrying bag', 'Studio Setup', 4, 0, 1),
('Wireless Microphone - Rode Wireless GO II', 'Compact wireless microphone system for video recording', 'Audio Equipment', 6, 0, 2),
('Monitors - Dell UltraSharp 27" (4K)', 'Professional 4K monitor for color-accurate editing', 'Computer Equipment', 3, 0, 2),
('USB-C Hub - Multi-Port Adapter', 'Aluminum USB-C hub with USB 3.0, HDMI, SD card reader', 'Computer Equipment', 10, 1, 2),
('Reflector - 5-in-1 Photography', 'Multi-purpose 5-in-1 reflector kit (gold, silver, white, black, diffuser)', 'Photography Equipment', 7, 0, 1),
('Lenovo ThinkPad Laptop', 'High-performance laptop for design and video editing work', 'Computer Equipment', 2, 0, 1),
('Wacom Pen Tablet - Cintiq 16"', 'Interactive pen display for digital design and illustration', 'Computer Equipment', 3, 1, 1),
('Paint & Swatch Library - Pantone Plus', 'Complete Pantone color matching system for design work', 'Design Tools', 5, 0, 0),
('Cable Organizer Kit', 'Collection of cable ties, clips, and organizers', 'Studio Supplies', 12, 0, 1),
('Portable Hard Drive - SSD 2TB', 'Fast portable SSD for project backup and file transfers', 'Storage', 8, 0, 2),
('Notebook & Sketchbook Set', 'Premium quality notebooks and sketchbooks for ideation', 'Design Tools', 20, 2, 3),
('Marker Set - Professional Design', 'Full set of professional markers for concept sketches and presentations', 'Design Tools', 10, 1, 2),
('Ring Light - 18" with Stand', 'Professional LED ring light for portrait and product photography', 'Lighting', 4, 0, 2),
('Memory Card - CF Express 128GB', 'High-speed memory cards for professional cameras', 'Storage', 6, 0, 1),
('Gaffer Tape - Professional Grade', 'Heavy-duty gaffer tape assortment in black and white', 'Studio Supplies', 25, 0, 5);
