INSERT INTO items (name, description, level, total, available, damaged, in_use, is_active, version_id, location) VALUES
('3D Printer (Resin)', 'High-detail resin 3D printer for precision prototypes.', 'staff', 3, 1, 1, 1, TRUE, 1, 'Prototype Lab A'),
('Soldering Station - Basic', 'Standard soldering iron and accessories for basic circuit assembly.', 'guest', 10, 6, 2, 2, TRUE, 1, 'Electronics Workshop'),
('CAD Software License (Floating)', 'Shared license for advanced Computer-Aided Design software.', 'intern', 15, 5, 0, 10, TRUE, 1, 'Software Server'),
('Oscilloscope - Benchtop', 'Four-channel digital storage oscilloscope for circuit debugging.', 'staff', 4, 2, 0, 2, TRUE, 1, 'Testing Bay 1'),
('VR Headset (Design Review)', 'Virtual Reality headset used for immersive 3D model reviews.', 'staff', 6, 3, 1, 2, TRUE, 1, 'Design Review Room'),
('Microcontroller Dev Kit (Arduino)', 'Starter development board for quick prototyping and testing.', 'guest', 25, 18, 3, 4, TRUE, 1, 'Component Storage Cabinet'),
('Component Library Access', 'Access credentials to the central electronic component vault.', 'admin', 1, 1, 0, 0, TRUE, 1, 'Vault (Digital)'),
('High-Res Wacom Tablet', 'Professional graphics tablet for sketching and texturing 3D models.', 'staff', 8, 2, 2, 4, TRUE, 1, 'Visual Design Studio'),
('3D Scanner (Handheld)', 'Portable device for capturing physical objects into digital 3D models.', 'staff', 2, 0, 0, 2, TRUE, 1, 'Metrology Station'),
('Lab Safety Goggles', 'Standard protective eyewear for the electronics lab area.', 'guest', 40, 35, 5, 0, TRUE, 1, 'Safety Station B'),
('Vector Network Analyzer (VNA)', 'Specialized equipment for measuring RF properties of electrical networks.', 'admin', 1, 0, 0, 1, TRUE, 1, 'RF Chamber 2'),
('Cloud Rendering Credits', 'Tokens for using external high-performance cloud rendering services.', 'intern', 5, 2, 0, 3, TRUE, 1, 'Software Server'),
('Logic Analyzer', 'Tool for capturing and analyzing digital signals from circuits.', 'staff', 3, 1, 0, 2, TRUE, 1, 'Testing Bay 2'),
('Precision Multimeter', 'High-accuracy digital multimeter for component measurements.', 'staff', 12, 7, 1, 4, TRUE, 1, 'Electronics Workshop'),
('Filament Spool - PLA', 'Standard PLA plastic filament for FDM 3D printing.', 'guest', 50, 45, 5, 0, TRUE, 1, 'Material Storage A'),
('Server Rack Access Key', 'Key for physical access to the main data server rack.', 'admin', 3, 3, 0, 0, TRUE, 1, 'Server Room 1'),
('Advanced Post-Processing Kit', 'Tools for sanding, curing, and finishing 3D prints.', 'intern', 7, 4, 1, 2, TRUE, 1, 'Finishing Room'),
('ESD Wrist Strap', 'Anti-static wrist strap for safe handling of sensitive electronics.', 'guest', 30, 20, 8, 2, TRUE, 1, 'Electronics Workshop'),
('Design Studio Hot Desk', 'Booking slot for a temporary workstation in the design area.', 'intern', 10, 3, 0, 7, TRUE, 1, 'Open Studio Floor'),
('Power Supply - Adjustable', 'Bench power supply for providing variable voltage to circuits.', 'staff', 5, 1, 0, 4, TRUE, 1, 'Testing Bay 1');
